spring.application.name=HealthClinicApp
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

clinic.db.url=mysql://127.0.0.1:3306/health_clinic_db?useSSL=false&serverTimezone=UTC
clinic.db.username=root
clinic.db.password=1234
clinic.db.maximum-pool-size=10
clinic.db.minimum-idle=2
clinic.console.enabled=true

spring.main.web-application-type=none
