spring.application.name=HealthClinicApp
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

clinic.db.url=jdbc:mysql://localhost:3306/health_clinic_db?useSSL=false&serverTimezone=UTC
clinic.db.username=clinic_app_user
clinic.db.password=StrongPassword123!
clinic.db.maximum-pool-size=10
clinic.db.minimum-idle=2
clinic.console.enabled=true

spring.main.web-application-type=none
